### ISSUE TITLE
Authentication token not found

### ISSUE THREAD

**Issue by charleshaa** [gillesdemey/Cumulus#16]
Hello,

When starting the app with `electron .` after a `grunt buid`, I get a blank window, and in the console: 

```
[3297:0916/135038:INFO:renderer_main.cc(200)] Renderer process started
registerProtocol API has been replaced by the register[File/Http/Buffer/String]Protocol API family, please switch to the new APIs.
[3295:0916/135038:INFO:CONSOLE(213)] "Uncaught Error: Refusing to initialize application, authentication token not found.", source: file:///Users/carlos/Cumulus/app/js/bundle.js (213)
```

Any ideas ?

**Comment by gillesdemey** [comment]
What is it you're trying to do? Just build the app, or run it in development mode to hack on it?

After running `grunt build` you can just run the app from the `dist` folder.

For development you might want to just run `grunt`, this will compile the sources and set up a watcher but not minify the code so you can still debug it.

You can then run it with `NODE_ENV=development electron .` in another tab or window.

Either way this error occurs because it can't find your SoundCloud token to log you in, which is created after you've logged in for the first time.

Relevant part of the source: https://github.com/gillesdemey/Cumulus/blob/master/app/js/app.js#L49

**Comment by ghs21** [comment]
Georges Strickaert
dotidam@gmail.com <mailto:dotidam@gmail.com>

Hello,

- I don’t understand : I found this email sent to Cumulus@noreply.github.com <mailto:Cumulus@noreply.github.com>, and this isn’t any of my email accounts ..

- I suggest you to check the reason why. And, if enough time, to advise.

Rgds
GS

===============================================================l=======================================================================================================================================

**Comment by gillesdemey** [comment]
I'm going to close this issue due to lack of response and I can't seem to be able to reproduce this
