### ISSUE TITLE
Add support for sets/playlists in liked & feed

### ISSUE THREAD

**Issue by kokarn** [gillesdemey/Cumulus#2]
I'd really like to be able to listen to sets/playlists that i get in my feed or that i have liked. 

Stuff like this: https://soundcloud.com/mau5trap/sets/enzos-summer-vibz
At the moment they don't seem to show up at all in either of those tabs.

Haven't been able to test the playlist tab yet as it just keeps loading and never shows anything at the moment.

**Comment by Bitbored** [comment]
Could you specify what kind of OS you use? The playlist not loading bug was unknown until now...

**Comment by kokarn** [comment]
Oh really? The tab one or that they don't show up in feed?

It's a pretty new macbook 13" with retina on 10.10.3.

**Comment by gillesdemey** [comment]
The playlists tab takes a long time to load depending on how many playlists/tracks you have.

You can check if the network request fails or if there's a JavaScript exception by running the app in development mode.

Basically:

* Clone the project
* Install dependencies `npm install && npm install -g electron-prebuilt`
* And run it `NODE_ENV=development electron .`

If patience doesn't work, it might be a technical issue :-)

There are also a few limitation to SoundCloud's public API, namely:
* You can't get a list of playlists that aren't curated by you
* Playlists in your feed show up as a flat list of tracks, so I can't group them like I do in the playlists tab.

I can probably get around some of those limitations, and I'll report back on progress regarding this issue here.

**Comment by gillesdemey** [comment]
I've implemented your feature request, and is available as v0.3.0.

You'll have to [download](https://www.dropbox.com/s/w5lo9fqsb4hwipr/Cumulus.zip?dl=0) the app again though!

I'll probably have another look at how playlists are currently displayed in the app, I'm not quite happy with it.

Regarding favorited sets: not currently possible to get them through SoundClouds official API, and I don't want to use their (undocumented) v2 API since it's against SoundCloud's Terms of Use and still very much in flux.

**Comment by kokarn** [comment]
This looks so good, thank you very much!

I'll open another issue for the playlists tab tho.
