### ISSUE TITLE
Custom Keyboard Shortcuts

### ISSUE THREAD

**Issue by killa-kyle** [gillesdemey/Cumulus#40]
It would be nice to be able to "Like" the current playing song with a keyboard shortcut.
I love the ability to go through my Soundcloud feed with the keyboard media buttons, and being able to like tracks as I hear them would be useful.

**Comment by gillesdemey** [comment]
I've contemplated this feature as well, unfortunately Atom's global shortcuts take over any other similar shortcut defined across your system so we'll have to some up with something pretty unique for Cumulus. Feel free to make a suggestion! :)

**Comment by andersfischernielsen** [comment]
Cmd+Alt+L doesn't seem to be used very often by apps on OS X. :)

**Comment by frdmn** [comment]
:+1:

**Comment by killa-kyle** [comment]
I submitted a pull request for this (#61). Went with @andersfischernielsen 's Cmd+Alt+L and it works well for me¯\_(ツ)_/¯

**Comment by seppestas** [comment]
This was fixed in #61

**Comment by FoxxMD** [comment]
Cmd+Alt+L is used by [Intellij](https://www.jetbrains.com/idea/) to reformat code. Took me forever to figure out Cumulus was hijacking it :/

**Comment by gillesdemey** [comment]
@FoxxMD I'm sorry this is happening to you, I hope this hasn't impacted your workflow too much.

I propose to add this behaviour as a setting that you have to opt-in to.

**Comment by seppestas** [comment]
To bad OSes (or at least macOS) don't have a way to centralize shortcuts for applications.

Imagine an API applications have to use to register all shortcuts and the scope in which they are used. This would allow the the OS to detect collisions and tell the user. Please, someone make this happen!

**Comment by FoxxMD** [comment]
@seppestas in a perfect world!

@gillesdemey It's no problem since I figured it out! 

Opt-in would definitely be a better behavior. 

Or document it in an obvious place inside the app or on the homepage. I shouldn't have to dig through github issues to find out there's a global shortcut that overrides everything else in my system ;) If I was a normal user (read: not a developer myself and unfamiliar with github) I'd be tearing my hair out by now.
